fix(card_scenes): prevent crash when entity_id is null
card_scenes could crash with the following error:

ButtonCardJSTemplateError: Cannot read properties of null (reading 'substr')